In [1]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as f

In [2]:
spark = SparkSession.builder \
    .appName("transform_population") \
    .master("local[*]") \
    .getOrCreate()

In [62]:
df = spark.read \
    .options(header=True, sep=r'\t') \
    .csv("population")
df.show()

+------------------+------+-----+------+------+------+-----+------+------+-----+------+------+------+
| indic_de,geo\time| 2008 |2009 | 2010 | 2011 | 2012 |2013 | 2014 | 2015 |2016 | 2017 | 2018 | 2019 |
+------------------+------+-----+------+------+------+-----+------+------+-----+------+------+------+
|       PC_Y0_14,AD| 14.6 |14.5 | 14.5 | 15.5 | 15.5 |15.5 |    : |    : |   : |    : |    : | 13.9 |
|       PC_Y0_14,AL| 24.1 |23.3 | 22.5 | 21.6 | 20.7 |20.1 | 19.6 | 19.0 |18.5 | 18.2 | 17.7 | 17.2 |
|       PC_Y0_14,AM| 19.0 |18.6 | 18.3 |    : |    : |   : |    : | 19.4 |19.6 | 20.0 | 20.2 | 20.2 |
|       PC_Y0_14,AT| 15.4 |15.1 | 14.9 | 14.7 | 14.6 |14.4 | 14.3 | 14.3 |14.3 | 14.4 | 14.4 | 14.4 |
|       PC_Y0_14,AZ| 23.2 |22.6 | 22.6 | 22.3 | 22.2 |22.3 | 22.4 | 22.4 |22.5 | 22.6 | 22.6 | 22.4 |
|       PC_Y0_14,BE| 16.9 |16.9 | 16.9 |17.0 b| 17.0 |17.0 | 17.0 | 17.0 |17.0 | 17.0 | 17.0 | 16.9 |
|       PC_Y0_14,BG| 13.1 |13.1 | 13.2 | 13.2 | 13.4 |13.6 | 13.7 | 13.9 |14.0 | 14.1 | 14.2 | 14.4 |
|       PC_Y0_14,BY| 14.7 |14.6 |    : | 14.9 | 15.1 |15.4 | 15.7 | 16.0 |16.3 | 16.6 | 16.8 | 16.9 |
|       PC_Y0_14,CH| 15.5 |15.3 | 15.2 |15.1 b| 15.0 |14.9 | 14.9 | 14.9 |14.9 | 14.9 | 15.0 | 15.0 |
|       PC_Y0_14,CY| 18.2 |17.7 | 17.2 | 16.8 | 16.5 |16.4 | 16.3 | 16.4 |16.4 | 16.3 | 16.2 | 16.1 |
|       PC_Y0_14,CZ| 14.2 |14.2 | 14.3 | 14.5 | 14.7 |14.8 | 15.0 | 15.2 |15.4 | 15.6 | 15.7 | 15.9 |
|       PC_Y0_14,DE| 13.7 |13.6 | 13.5 |13.6 b| 13.4 |13.3 |13.2 b| 13.2 |13.2 | 13.4 | 13.5 | 13.6 |
|       PC_Y0_14,DK| 18.4 |18.3 | 18.1 | 17.9 | 17.7 |17.4 | 17.2 | 17.0 |16.8 | 16.7 | 16.6 | 16.5 |
|     PC_Y0_14,EA18| 15.4 |15.4 | 15.4 |15.4 b|15.4 b|15.3 |15.3 b|15.2 b|15.1 |15.1 b|15.0 p|15.0 p|
|     PC_Y0_14,EA19| 15.5 |15.5 | 15.4 |15.5 b|15.4 b|15.4 |15.3 b|15.3 b|15.2 |15.2 b|15.1 p|15.0 p|
|       PC_Y0_14,EE| 14.8 |14.9 | 15.1 | 15.3 | 15.5 |15.7 | 15.8 |15.9 b|16.1 | 16.2 | 16.3 | 16.4 |
|       PC_Y0_14,EL| 14.6 |14.6 | 14.6 | 14.6 | 14.7 |14.7 | 14.6 | 14.5 |14.4 | 14.4 | 14.4 | 14.3 |
|       PC_Y0_14,ES| 14.6 |14.8 | 14.9 | 15.0 | 15.1 |15.2 | 15.2 | 15.2 |15.1 | 15.1 | 15.0 | 14.8 |
|PC_Y0_14,EU27_2007|15.8 b|15.7 |15.7 b|15.7 b|15.7 b|15.7 |15.6 b|15.6 b|15.6 |15.6 b|15.6 p|15.5 p|
|PC_Y0_14,EU27_2020|15.5 b|15.4 |15.4 b|15.4 b|15.4 b|15.4 |15.3 b|15.3 b|15.3 |15.2 b|15.2 p|15.2 p|
+------------------+------+-----+------+------+------+-----+------+------+-----+------+------+------+
only showing top 20 rows

In [63]:
df.show()

+------------------+------+-----+------+------+------+-----+------+------+-----+------+------+------+
| indic_de,geo\time| 2008 |2009 | 2010 | 2011 | 2012 |2013 | 2014 | 2015 |2016 | 2017 | 2018 | 2019 |
+------------------+------+-----+------+------+------+-----+------+------+-----+------+------+------+
|       PC_Y0_14,AD| 14.6 |14.5 | 14.5 | 15.5 | 15.5 |15.5 |    : |    : |   : |    : |    : | 13.9 |
|       PC_Y0_14,AL| 24.1 |23.3 | 22.5 | 21.6 | 20.7 |20.1 | 19.6 | 19.0 |18.5 | 18.2 | 17.7 | 17.2 |
|       PC_Y0_14,AM| 19.0 |18.6 | 18.3 |    : |    : |   : |    : | 19.4 |19.6 | 20.0 | 20.2 | 20.2 |
|       PC_Y0_14,AT| 15.4 |15.1 | 14.9 | 14.7 | 14.6 |14.4 | 14.3 | 14.3 |14.3 | 14.4 | 14.4 | 14.4 |
|       PC_Y0_14,AZ| 23.2 |22.6 | 22.6 | 22.3 | 22.2 |22.3 | 22.4 | 22.4 |22.5 | 22.6 | 22.6 | 22.4 |
|       PC_Y0_14,BE| 16.9 |16.9 | 16.9 |17.0 b| 17.0 |17.0 | 17.0 | 17.0 |17.0 | 17.0 | 17.0 | 16.9 |
|       PC_Y0_14,BG| 13.1 |13.1 | 13.2 | 13.2 | 13.4 |13.6 | 13.7 | 13.9 |14.0 | 14.1 | 14.2 | 14.4 |
|       PC_Y0_14,BY| 14.7 |14.6 |    : | 14.9 | 15.1 |15.4 | 15.7 | 16.0 |16.3 | 16.6 | 16.8 | 16.9 |
|       PC_Y0_14,CH| 15.5 |15.3 | 15.2 |15.1 b| 15.0 |14.9 | 14.9 | 14.9 |14.9 | 14.9 | 15.0 | 15.0 |
|       PC_Y0_14,CY| 18.2 |17.7 | 17.2 | 16.8 | 16.5 |16.4 | 16.3 | 16.4 |16.4 | 16.3 | 16.2 | 16.1 |
|       PC_Y0_14,CZ| 14.2 |14.2 | 14.3 | 14.5 | 14.7 |14.8 | 15.0 | 15.2 |15.4 | 15.6 | 15.7 | 15.9 |
|       PC_Y0_14,DE| 13.7 |13.6 | 13.5 |13.6 b| 13.4 |13.3 |13.2 b| 13.2 |13.2 | 13.4 | 13.5 | 13.6 |
|       PC_Y0_14,DK| 18.4 |18.3 | 18.1 | 17.9 | 17.7 |17.4 | 17.2 | 17.0 |16.8 | 16.7 | 16.6 | 16.5 |
|     PC_Y0_14,EA18| 15.4 |15.4 | 15.4 |15.4 b|15.4 b|15.3 |15.3 b|15.2 b|15.1 |15.1 b|15.0 p|15.0 p|
|     PC_Y0_14,EA19| 15.5 |15.5 | 15.4 |15.5 b|15.4 b|15.4 |15.3 b|15.3 b|15.2 |15.2 b|15.1 p|15.0 p|
|       PC_Y0_14,EE| 14.8 |14.9 | 15.1 | 15.3 | 15.5 |15.7 | 15.8 |15.9 b|16.1 | 16.2 | 16.3 | 16.4 |
|       PC_Y0_14,EL| 14.6 |14.6 | 14.6 | 14.6 | 14.7 |14.7 | 14.6 | 14.5 |14.4 | 14.4 | 14.4 | 14.3 |
|       PC_Y0_14,ES| 14.6 |14.8 | 14.9 | 15.0 | 15.1 |15.2 | 15.2 | 15.2 |15.1 | 15.1 | 15.0 | 14.8 |
|PC_Y0_14,EU27_2007|15.8 b|15.7 |15.7 b|15.7 b|15.7 b|15.7 |15.6 b|15.6 b|15.6 |15.6 b|15.6 p|15.5 p|
|PC_Y0_14,EU27_2020|15.5 b|15.4 |15.4 b|15.4 b|15.4 b|15.4 |15.3 b|15.3 b|15.3 |15.2 b|15.2 p|15.2 p|
+------------------+------+-----+------+------+------+-----+------+------+-----+------+------+------+
only showing top 20 rows

In [64]:
df1 = df.select(f.col(r'indic_de,geo\time').alias('code'), f.col('2019 ').alias('Y2019')) \
    .withColumn('country_code', f.split('code', ',')[1]) \
    .withColumn('ages_group', f.split((f.split('code', ',')[0]), 'Y')[1])

df1.show(50)

+------------------+------+------------+----------+
|              code| Y2019|country_code|ages_group|
+------------------+------+------------+----------+
|       PC_Y0_14,AD| 13.9 |          AD|      0_14|
|       PC_Y0_14,AL| 17.2 |          AL|      0_14|
|       PC_Y0_14,AM| 20.2 |          AM|      0_14|
|       PC_Y0_14,AT| 14.4 |          AT|      0_14|
|       PC_Y0_14,AZ| 22.4 |          AZ|      0_14|
|       PC_Y0_14,BE| 16.9 |          BE|      0_14|
|       PC_Y0_14,BG| 14.4 |          BG|      0_14|
|       PC_Y0_14,BY| 16.9 |          BY|      0_14|
|       PC_Y0_14,CH| 15.0 |          CH|      0_14|
|       PC_Y0_14,CY| 16.1 |          CY|      0_14|
|       PC_Y0_14,CZ| 15.9 |          CZ|      0_14|
|       PC_Y0_14,DE| 13.6 |          DE|      0_14|
|       PC_Y0_14,DK| 16.5 |          DK|      0_14|
|     PC_Y0_14,EA18|15.0 p|        EA18|      0_14|
|     PC_Y0_14,EA19|15.0 p|        EA19|      0_14|
|       PC_Y0_14,EE| 16.4 |          EE|      0_14|
|       PC_Y0_14,EL| 14.3 |          EL|      0_14|
|       PC_Y0_14,ES| 14.8 |          ES|      0_14|
|PC_Y0_14,EU27_2007|15.5 p|   EU27_2007|      0_14|
|PC_Y0_14,EU27_2020|15.2 p|   EU27_2020|      0_14|
|     PC_Y0_14,EU28|15.5 p|        EU28|      0_14|
|       PC_Y0_14,FI| 16.0 |          FI|      0_14|
|       PC_Y0_14,FR|18.0 p|          FR|      0_14|
|       PC_Y0_14,FX|    : |          FX|      0_14|
|       PC_Y0_14,GE| 20.3 |          GE|      0_14|
|       PC_Y0_14,HR| 14.4 |          HR|      0_14|
|       PC_Y0_14,HU| 14.5 |          HU|      0_14|
|       PC_Y0_14,IE|20.5 e|          IE|      0_14|
|       PC_Y0_14,IS| 19.0 |          IS|      0_14|
|       PC_Y0_14,IT| 13.2 |          IT|      0_14|
|       PC_Y0_14,LI| 14.7 |          LI|      0_14|
|       PC_Y0_14,LT| 15.1 |          LT|      0_14|
|       PC_Y0_14,LU| 16.1 |          LU|      0_14|
|       PC_Y0_14,LV| 15.9 |          LV|      0_14|
|       PC_Y0_14,MD|    : |          MD|      0_14|
|       PC_Y0_14,ME| 18.0 |          ME|      0_14|
|       PC_Y0_14,MK| 16.4 |          MK|      0_14|
|       PC_Y0_14,MT| 13.7 |          MT|      0_14|
|       PC_Y0_14,NL| 15.9 |          NL|      0_14|
|       PC_Y0_14,NO| 17.5 |          NO|      0_14|
|       PC_Y0_14,PL| 15.4 |          PL|      0_14|
|       PC_Y0_14,PT| 13.7 |          PT|      0_14|
|       PC_Y0_14,RO| 15.7 |          RO|      0_14|
|       PC_Y0_14,RS| 14.3 |          RS|      0_14|
|       PC_Y0_14,RU|    : |          RU|      0_14|
|       PC_Y0_14,SE| 17.8 |          SE|      0_14|
|       PC_Y0_14,SI| 15.1 |          SI|      0_14|
|       PC_Y0_14,SK| 15.7 |          SK|      0_14|
|       PC_Y0_14,SM|    : |          SM|      0_14|
|       PC_Y0_14,TR| 23.4 |          TR|      0_14|
+------------------+------+------------+----------+
only showing top 50 rows

In [65]:
df1.createOrReplaceTempView('population')

In [66]:
spark.sql("""
SELECT distinct ages_group
FROM population
""").show()

+----------+
|ages_group|
+----------+
|     65_79|
|      0_14|
|     50_64|
|     15_24|
|    80_MAX|
|     25_49|
+----------+

In [67]:
df_population_pivot = spark.sql("""
SELECT cast(regexp_replace(Y2019, '[a-z]', '') as decimal(10,2) ) Y2019, country_code, ages_group
FROM population
WHERE length(country_code) == 2 
""").groupBy('country_code').pivot('ages_group').max('Y2019') \
    .withColumn('sum', f.col('0_14')+f.col('15_24')+f.col('25_49')+f.col('50_64')+f.col('65_79')+f.col('80_MAX')) \
    .orderBy('country_code')


df_population_pivot.show(100)

+------------+-----+-----+-----+-----+-----+------+------+
|country_code| 0_14|15_24|25_49|50_64|65_79|80_MAX|   sum|
+------------+-----+-----+-----+-----+-----+------+------+
|          AD|13.90|10.60|39.40|22.50|10.20|  3.40|100.00|
|          AL|17.20|15.50|33.00|20.20|11.40|  2.70|100.00|
|          AM|20.20|11.80|36.90|19.10| 9.00|  3.00|100.00|
|          AT|14.40|10.90|34.00|21.70|13.80|  5.00| 99.80|
|          AZ|22.40|14.10|39.10|17.60| 5.30|  1.50|100.00|
|          BE|16.90|11.40|32.70|20.10|13.30|  5.60|100.00|
|          BG|14.40| 8.90|35.00|20.40|16.50|  4.80|100.00|
|          BY|16.90| 9.90|36.60|21.30|11.30|  3.90| 99.90|
|          CH|15.00|10.60|35.00|20.90|13.30|  5.20|100.00|
|          CY|16.10|12.80|37.10|17.90|12.50|  3.70|100.10|
|          CZ|15.90| 9.10|36.70|18.80|15.50|  4.10|100.10|
|          DE|13.60|10.40|31.60|22.80|15.10|  6.50|100.00|
|          DK|16.50|12.60|31.70|19.60|15.00|  4.50| 99.90|
|          EE|16.40| 9.50|34.90|19.40|14.10|  5.60| 99.90|
|          EL|14.30|10.20|33.10|20.30|14.90|  7.10| 99.90|
|          ES|14.80| 9.80|35.30|20.70|13.30|  6.10|100.00|
|          FI|16.00|11.20|31.20|19.90|16.30|  5.50|100.10|
|          FR|18.00|11.70|31.00|19.20|14.00|  6.10|100.00|
|          FX| null| null| null| null| null|  null|  null|
|          GE|20.30|11.50|33.90|19.50|11.40|  3.50|100.10|
|          HR|14.40|10.90|32.50|21.60|15.20|  5.30| 99.90|
|          HU|14.50|10.70|35.80|19.60|14.90|  4.40| 99.90|
|          IE|20.50|12.60|35.60|17.20|10.80|  3.30|100.00|
|          IS|19.00|13.40|35.50|17.90|10.70|  3.50|100.00|
|          IT|13.20| 9.80|32.40|21.90|15.70|  7.20|100.20|
|          LI|14.70|10.90|33.30|23.20|14.10|  3.80|100.00|
|          LT|15.10|10.50|32.70|21.90|14.00|  5.80|100.00|
|          LU|16.10|11.60|38.20|19.80|10.40|  4.00|100.10|
|          LV|15.90| 9.20|33.80|20.90|14.70|  5.60|100.10|
|          MD| null| null| null| null| null|  null|  null|
|          ME|18.00|13.00|34.20|19.80|11.90|  3.30|100.20|
|          MK|16.40|12.40|37.50|19.70|11.50|  2.50|100.00|
|          MT|13.70|11.00|38.50|18.20|14.50|  4.20|100.10|
|          NL|15.90|12.30|31.80|20.90|14.60|  4.60|100.10|
|          NO|17.50|12.40|34.10|18.70|13.00|  4.20| 99.90|
|          PL|15.40|10.30|37.00|19.70|13.30|  4.40|100.10|
|          PT|13.70|10.60|32.90|20.90|15.40|  6.40| 99.90|
|          RO|15.70|10.60|35.60|19.70|13.90|  4.70|100.20|
|          RS|14.30|10.50|33.80|20.90|15.80|  4.60| 99.90|
|          RU| null| null| null| null| null|  null|  null|
|          SE|17.80|11.30|32.90|18.10|14.80|  5.10|100.00|
|          SI|15.10| 9.40|34.10|21.60|14.50|  5.30|100.00|
|          SK|15.70|10.40|38.10|19.70|12.70|  3.30| 99.90|
|          SM| null| null| null| null| null|  null|  null|
|          TR|23.40|15.80|37.00|15.00| 7.00|  1.80|100.00|
|          UA|15.40| 9.60|37.60|20.60|12.50|  4.30|100.00|
|          UK|17.90|11.80|32.80|19.10|13.40|  5.00|100.00|
|          XK|24.40|17.80|35.20|14.10| 6.80|  1.80|100.10|
+------------+-----+-----+-----+-----+-----+------+------+

In [69]:
df_population_pivot.createOrReplaceTempView('population_pivot')

In [70]:
df_country_lookup = spark.read \
    .options(header=True, sep=',') \
    .csv('dim_country/')
df_country_lookup.show()
df_country_lookup.createOrReplaceTempView('country_lookup')

+--------------------+--------------------+--------------------+---------+----------+
|             country|country_code_2_digit|country_code_3_digit|continent|population|
+--------------------+--------------------+--------------------+---------+----------+
|               Aruba|                  AW|                 ABW|  America|    106766|
|         Afghanistan|                  AF|                 AFG|     Asia|  38928341|
|              Angola|                  AO|                 AGO|   Africa|  32866268|
|            Anguilla|                  AI|                 AIA|  America|     15002|
|             Albania|                  AL|                 ALB|   Europe|   2862427|
|             Andorra|                  AD|                 AND|   Europe|     76177|
|United Arab Emirates|                  AE|                 ARE|     Asia|   9890400|
|           Argentina|                  AR|                 ARG|  America|  45195777|
|             Armenia|                  AM|                 ARM|   Europe|   2963234|
| Antigua and Barbuda|                  AG|                 ATG|  America|     97928|
|           Australia|                  AU|                 AUS|  Oceania|  25499881|
|             Austria|                  AT|                 AUT|   Europe|   8858775|
|          Azerbaijan|                  AZ|                 AZE|   Europe|  10139175|
|             Burundi|                  BI|                 BDI|   Africa|  11890781|
|             Belgium|                  BE|                 BEL|   Europe|  11455519|
|               Benin|                  BJ|                 BEN|   Africa|  12123198|
|Bonaire, Saint Eu...|                  BQ|                 BES|  America|     26221|
|        Burkina Faso|                  BF|                 BFA|   Africa|  20903278|
|          Bangladesh|                  BD|                 BGD|     Asia| 164689383|
|            Bulgaria|                  BG|                 BGR|   Europe|   7000039|
+--------------------+--------------------+--------------------+---------+----------+
only showing top 20 rows

In [72]:
df_processed_population = spark.sql("""
SELECT c.country,
       c.country_code_2_digit,
       c.country_code_3_digit,
       c.population,
       p.0_14  AS age_group_0_14,
       p.15_24 AS age_group_15_24,
       p.25_49 AS age_group_25_49,
       p.50_64 AS age_group_50_64, 
       p.65_79 AS age_group_65_79,
       p.80_MAX AS age_group_80_max
FROM population_pivot p JOIN country_lookup c ON p.country_code = c.country_code_2_digit
ORDER BY c.country
""")
df_processed_population.show(truncate=False)

+----------+--------------------+--------------------+----------+--------------+---------------+---------------+---------------+---------------+----------------+
|country   |country_code_2_digit|country_code_3_digit|population|age_group_0_14|age_group_15_24|age_group_25_49|age_group_50_64|age_group_65_79|age_group_80_max|
+----------+--------------------+--------------------+----------+--------------+---------------+---------------+---------------+---------------+----------------+
|Albania   |AL                  |ALB                 |2862427   |17.20         |15.50          |33.00          |20.20          |11.40          |2.70            |
|Andorra   |AD                  |AND                 |76177     |13.90         |10.60          |39.40          |22.50          |10.20          |3.40            |
|Armenia   |AM                  |ARM                 |2963234   |20.20         |11.80          |36.90          |19.10          |9.00           |3.00            |
|Austria   |AT                  |AUT                 |8858775   |14.40         |10.90          |34.00          |21.70          |13.80          |5.00            |
|Azerbaijan|AZ                  |AZE                 |10139175  |22.40         |14.10          |39.10          |17.60          |5.30           |1.50            |
|Belarus   |BY                  |BLR                 |9449321   |16.90         |9.90           |36.60          |21.30          |11.30          |3.90            |
|Belgium   |BE                  |BEL                 |11455519  |16.90         |11.40          |32.70          |20.10          |13.30          |5.60            |
|Bulgaria  |BG                  |BGR                 |7000039   |14.40         |8.90           |35.00          |20.40          |16.50          |4.80            |
|Croatia   |HR                  |HRV                 |4076246   |14.40         |10.90          |32.50          |21.60          |15.20          |5.30            |
|Cyprus    |CY                  |CYP                 |875899    |16.10         |12.80          |37.10          |17.90          |12.50          |3.70            |
|Czechia   |CZ                  |CZE                 |10649800  |15.90         |9.10           |36.70          |18.80          |15.50          |4.10            |
|Denmark   |DK                  |DNK                 |5806081   |16.50         |12.60          |31.70          |19.60          |15.00          |4.50            |
|Estonia   |EE                  |EST                 |1324820   |16.40         |9.50           |34.90          |19.40          |14.10          |5.60            |
|Finland   |FI                  |FIN                 |5517919   |16.00         |11.20          |31.20          |19.90          |16.30          |5.50            |
|France    |FR                  |FRA                 |67012883  |18.00         |11.70          |31.00          |19.20          |14.00          |6.10            |
|Georgia   |GE                  |GEO                 |3989175   |20.30         |11.50          |33.90          |19.50          |11.40          |3.50            |
|Germany   |DE                  |DEU                 |83019213  |13.60         |10.40          |31.60          |22.80          |15.10          |6.50            |
|Greece    |EL                  |GRC                 |10724599  |14.30         |10.20          |33.10          |20.30          |14.90          |7.10            |
|Hungary   |HU                  |HUN                 |9772756   |14.50         |10.70          |35.80          |19.60          |14.90          |4.40            |
|Iceland   |IS                  |ISL                 |356991    |19.00         |13.40          |35.50          |17.90          |10.70          |3.50            |
+----------+--------------------+--------------------+----------+--------------+---------------+---------------+---------------+---------------+----------------+
only showing top 20 rows